-- Sous — T18: plant-based mains (6 vegan + 2 vegetarian) so a strict
-- dietary filter (T4) still leaves a usable rotation. Same seed pattern as
-- the original catalog; idempotent (guarded inserts).

-- New ingredients.
insert into ingredients (name_canonical, aliases, unit_default, source_hint, seasonal_months, is_free, allergens) values
  ('extra-firm tofu', '{"firm tofu","tofu"}', 'block', 'grocery', null, false, '{"soy"}'),
  ('red lentils', '{"split red lentils","masoor dal"}', 'cup', 'grocery', null, false, '{}'),
  ('tahini', '{"sesame paste"}', 'tbsp', 'grocery', null, false, '{"sesame"}'),
  ('paneer', '{"indian cheese"}', 'oz', 'grocery', null, false, '{"dairy"}'),
  ('ghee', '{"clarified butter"}', 'tbsp', 'grocery', null, false, '{"dairy"}'),
  ('garam masala', '{}', 'tsp', 'grocery', null, false, '{}'),
  ('ground turmeric', '{"turmeric powder"}', 'tsp', 'grocery', null, false, '{}'),
  ('vegetable broth', '{"vegetable stock"}', 'cup', 'grocery', null, false, '{}'),
  ('berbere spice blend', '{"berbere"}', 'tbsp', 'grocery', null, false, '{}')
on conflict (name_canonical) do nothing;

-- Recipes.
insert into recipes (title, cuisine_tag, body_md, time_minutes, toddler_variant_notes, source, base_servings, dietary_tags)
select v.title, v.cuisine_tag, v.body_md, v.time_minutes, v.notes, 'curated', v.base_servings, v.dietary_tags::text[]
from (values
  ('Black Bean & Sweet Potato Tacos', 'mexican', E'Smoky roasted sweet potato and spiced black beans piled into warm corn tortillas with avocado and lime.\n\n1. Roast diced sweet potato with olive oil, cumin, chili powder, and smoked paprika at 425F for 20 minutes.\n2. Warm black beans in a skillet with a splash of water and a pinch of salt until saucy.\n3. Char corn tortillas directly over a burner or in a dry skillet.\n4. Assemble tacos with sweet potato, beans, shredded cabbage, avocado, cilantro, and lime.', 30, E'Set aside plain roasted sweet potato cubes and rinsed black beans (mixed before spicing) in a soft tortilla or on their own; skip jalapeno and lime juice.', 4, '{"vegan","vegetarian","dairy_free","gluten_free"}'),
  ('Creamy Mushroom Spinach Gnocchi', 'italian', E'Pillowy gnocchi tossed with garlicky mushrooms, wilted spinach, and a light parmesan cream sauce.\n\n1. Boil gnocchi until they float, then drain and set aside.\n2. Saute onion and mushrooms in olive oil until browned, then add garlic and oregano.\n3. Stir in heavy cream and parmesan, simmer until slightly thickened.\n4. Fold in spinach and gnocchi, tossing until the spinach wilts and everything is coated.', 30, E'Reserve plain boiled gnocchi with a little butter and parmesan before mixing in mushrooms and pepper.', 4, '{"vegetarian","contains_dairy","contains_gluten"}'),
  ('Chana Masala with Spinach', 'indian', E'A weeknight chickpea curry simmered in a spiced tomato base with wilted spinach, served over rice.\n\n1. Saute onion until golden, then add garlic, ginger, cumin, turmeric, and garam masala.\n2. Stir in crushed tomatoes and simmer 5 minutes to deepen the flavor.\n3. Add chickpeas and simmer 10 minutes, then stir in spinach until wilted.\n4. Season with salt and serve over rice with cilantro and lime.', 35, E'Scoop out a portion of chickpeas and rice before adding chili powder; mash lightly for easier eating.', 4, '{"vegan","vegetarian","dairy_free","gluten_free"}'),
  ('Gochujang Tofu & Broccoli Stir-Fry', 'asian', E'Crispy cornstarch-dusted tofu and broccoli tossed in a sweet-spicy gochujang glaze over rice.\n\n1. Press and cube tofu, toss in cornstarch, and pan-fry until crisp on all sides.\n2. Stir-fry broccoli and carrot in vegetable oil until crisp-tender.\n3. Whisk gochujang, soy sauce, sesame oil, garlic, and ginger into a sauce.\n4. Return tofu to the pan, add sauce, and toss to coat; serve over rice with scallions and sesame seeds.', 25, E'Set aside plain crispy tofu cubes and steamed broccoli before adding the gochujang sauce.', 4, '{"vegan","vegetarian","dairy_free","contains_soy","contains_gluten"}'),
  ('Harissa Chickpea & Eggplant Stew with Tahini', 'mediterranean', E'A smoky, harissa-spiced chickpea and eggplant stew finished with a tahini drizzle and lemon.\n\n1. Saute cubed eggplant in olive oil until golden and softened; set aside.\n2. In the same pot, saute onion and garlic, then stir in harissa and cumin.\n3. Add crushed tomatoes, vegetable broth, chickpeas, and eggplant; simmer 15 minutes.\n4. Season with salt and lemon, drizzle with tahini, and garnish with parsley.', 40, E'Reserve plain roasted eggplant and chickpeas, lightly mashed, before adding harissa; finish only with a small drizzle of tahini.', 4, '{"vegan","vegetarian","dairy_free","gluten_free"}'),
  ('Thai Red Curry with Tofu, Bok Choy & Snap Peas', 'asian', E'A fragrant coconut red curry with pan-seared tofu, bok choy, snap peas, and bell pepper over rice.\n\n1. Pan-fry cubed tofu in vegetable oil until golden on all sides; set aside.\n2. Saute red curry paste in the same pan for 1 minute until fragrant.\n3. Stir in coconut milk, soy sauce, and brown sugar, then add bell pepper and carrot; simmer 5 minutes.\n4. Add bok choy, snap peas, and tofu; simmer until just tender, then finish with lime and basil over rice.', 30, E'Set aside plain seared tofu and steamed vegetables with rice before adding curry paste; spoon over a little plain coconut milk broth only.', 4, '{"vegan","vegetarian","dairy_free","contains_soy","contains_gluten"}'),
  ('Palak Paneer', 'indian', E'Soft seared paneer cubes simmered in a silky spiced spinach sauce, finished with a touch of cream.\n\n1. Saute onion, garlic, and ginger in ghee until soft, then add cumin, garam masala, and turmeric.\n2. Add spinach and a splash of water, cook until wilted, then blend or mash into a smooth sauce.\n3. In a separate pan, sear paneer cubes in ghee until lightly golden.\n4. Combine paneer with the spinach sauce, stir in cream, and simmer 5 minutes; serve with rice.', 35, E'Set aside plain seared paneer cubes and a mild portion of the spinach sauce before adding extra spice; serve mixed with rice.', 4, '{"vegetarian","contains_dairy","gluten_free"}'),
  ('Ethiopian-Style Red Lentil Stew (Misir Wot)', 'other', E'A deeply spiced red lentil stew built on slow-caramelized onion and berbere, served over rice.\n\n1. Cook onion in vegetable oil over medium-low heat, stirring often, until deeply softened and golden, about 10 minutes.\n2. Stir in garlic, ginger, and berbere spice blend, cooking 1 minute until fragrant.\n3. Add crushed tomatoes, vegetable broth, and red lentils; simmer 20 minutes, stirring occasionally, until lentils are tender and stew has thickened.\n4. Season with salt and serve over rice.', 35, E'Cook a portion of onion, lentils, and broth before adding berbere; serve plain over rice.', 4, '{"vegan","vegetarian","dairy_free","gluten_free"}')
) as v(title, cuisine_tag, body_md, time_minutes, notes, base_servings, dietary_tags)
where not exists (select 1 from recipes r where r.title = v.title);

-- Recipe ingredients (resolve names -> ids).
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit, optional)
select r.id, i.id, v.quantity, v.unit, v.optional
from (values
  ('Black Bean & Sweet Potato Tacos', 'sweet potato', 2, 'each', false),
  ('Black Bean & Sweet Potato Tacos', 'black beans', 2, 'can', false),
  ('Black Bean & Sweet Potato Tacos', 'corn tortillas', 8, 'each', false),
  ('Black Bean & Sweet Potato Tacos', 'red onion', 0.5, 'each', false),
  ('Black Bean & Sweet Potato Tacos', 'avocado', 1, 'each', false),
  ('Black Bean & Sweet Potato Tacos', 'lime', 2, 'each', false),
  ('Black Bean & Sweet Potato Tacos', 'cilantro', 1, 'bunch', false),
  ('Black Bean & Sweet Potato Tacos', 'ground cumin', 1, 'tsp', false),
  ('Black Bean & Sweet Potato Tacos', 'chili powder', 1, 'tsp', false),
  ('Black Bean & Sweet Potato Tacos', 'smoked paprika', 0.5, 'tsp', false),
  ('Black Bean & Sweet Potato Tacos', 'olive oil', 2, 'tbsp', false),
  ('Black Bean & Sweet Potato Tacos', 'kosher salt', 1, 'tsp', false),
  ('Black Bean & Sweet Potato Tacos', 'jalapeno', 1, 'each', true),
  ('Black Bean & Sweet Potato Tacos', 'green cabbage', 1, 'cup', true),
  ('Creamy Mushroom Spinach Gnocchi', 'gnocchi', 1, 'lb', false),
  ('Creamy Mushroom Spinach Gnocchi', 'mushroom', 8, 'oz', false),
  ('Creamy Mushroom Spinach Gnocchi', 'baby spinach', 3, 'cup', false),
  ('Creamy Mushroom Spinach Gnocchi', 'garlic', 3, 'clove', false),
  ('Creamy Mushroom Spinach Gnocchi', 'yellow onion', 0.5, 'each', false),
  ('Creamy Mushroom Spinach Gnocchi', 'heavy cream', 0.75, 'cup', false),
  ('Creamy Mushroom Spinach Gnocchi', 'parmesan', 0.5, 'cup', false),
  ('Creamy Mushroom Spinach Gnocchi', 'olive oil', 2, 'tbsp', false),
  ('Creamy Mushroom Spinach Gnocchi', 'dried oregano', 0.5, 'tsp', false),
  ('Creamy Mushroom Spinach Gnocchi', 'kosher salt', 1, 'tsp', false),
  ('Creamy Mushroom Spinach Gnocchi', 'black pepper', 0.25, 'tsp', false),
  ('Chana Masala with Spinach', 'chickpeas', 2, 'can', false),
  ('Chana Masala with Spinach', 'baby spinach', 3, 'cup', false),
  ('Chana Masala with Spinach', 'crushed tomatoes', 1, 'can', false),
  ('Chana Masala with Spinach', 'yellow onion', 1, 'each', false),
  ('Chana Masala with Spinach', 'garlic', 3, 'clove', false),
  ('Chana Masala with Spinach', 'fresh ginger', 1, 'tbsp', false),
  ('Chana Masala with Spinach', 'garam masala', 1, 'tsp', false),
  ('Chana Masala with Spinach', 'ground cumin', 1, 'tsp', false),
  ('Chana Masala with Spinach', 'ground turmeric', 0.5, 'tsp', false),
  ('Chana Masala with Spinach', 'chili powder', 0.5, 'tsp', true),
  ('Chana Masala with Spinach', 'vegetable oil', 2, 'tbsp', false),
  ('Chana Masala with Spinach', 'kosher salt', 1, 'tsp', false),
  ('Chana Masala with Spinach', 'white rice', 1.5, 'cup', false),
  ('Chana Masala with Spinach', 'cilantro', 1, 'bunch', true),
  ('Chana Masala with Spinach', 'lime', 1, 'each', true),
  ('Gochujang Tofu & Broccoli Stir-Fry', 'extra-firm tofu', 1, 'block', false),
  ('Gochujang Tofu & Broccoli Stir-Fry', 'broccoli', 3, 'cup', false),
  ('Gochujang Tofu & Broccoli Stir-Fry', 'carrot', 1, 'each', false),
  ('Gochujang Tofu & Broccoli Stir-Fry', 'garlic', 2, 'clove', false),
  ('Gochujang Tofu & Broccoli Stir-Fry', 'fresh ginger', 1, 'tsp', false),
  ('Gochujang Tofu & Broccoli Stir-Fry', 'gochujang', 2, 'tbsp', false),
  ('Gochujang Tofu & Broccoli Stir-Fry', 'soy sauce', 2, 'tbsp', false),
  ('Gochujang Tofu & Broccoli Stir-Fry', 'sesame oil', 1, 'tbsp', false),
  ('Gochujang Tofu & Broccoli Stir-Fry', 'cornstarch', 2, 'tbsp', false),
  ('Gochujang Tofu & Broccoli Stir-Fry', 'vegetable oil', 2, 'tbsp', false),
  ('Gochujang Tofu & Broccoli Stir-Fry', 'scallion', 2, 'each', false),
  ('Gochujang Tofu & Broccoli Stir-Fry', 'sesame seeds', 1, 'tsp', true),
  ('Gochujang Tofu & Broccoli Stir-Fry', 'white rice', 1.5, 'cup', false),
  ('Harissa Chickpea & Eggplant Stew with Tahini', 'eggplant', 1, 'each', false),
  ('Harissa Chickpea & Eggplant Stew with Tahini', 'chickpeas', 2, 'can', false),
  ('Harissa Chickpea & Eggplant Stew with Tahini', 'crushed tomatoes', 1, 'can', false),
  ('Harissa Chickpea & Eggplant Stew with Tahini', 'yellow onion', 1, 'each', false),
  ('Harissa Chickpea & Eggplant Stew with Tahini', 'garlic', 3, 'clove', false),
  ('Harissa Chickpea & Eggplant Stew with Tahini', 'harissa', 2, 'tbsp', false),
  ('Harissa Chickpea & Eggplant Stew with Tahini', 'tahini', 3, 'tbsp', false),
  ('Harissa Chickpea & Eggplant Stew with Tahini', 'vegetable broth', 1, 'cup', false),
  ('Harissa Chickpea & Eggplant Stew with Tahini', 'olive oil', 3, 'tbsp', false),
  ('Harissa Chickpea & Eggplant Stew with Tahini', 'ground cumin', 1, 'tsp', false),
  ('Harissa Chickpea & Eggplant Stew with Tahini', 'kosher salt', 1, 'tsp', false),
  ('Harissa Chickpea & Eggplant Stew with Tahini', 'parsley', 0.25, 'cup', true),
  ('Harissa Chickpea & Eggplant Stew with Tahini', 'lemon', 1, 'each', false),
  ('Harissa Chickpea & Eggplant Stew with Tahini', 'white rice', 1.5, 'cup', true),
  ('Thai Red Curry with Tofu, Bok Choy & Snap Peas', 'extra-firm tofu', 1, 'block', false),
  ('Thai Red Curry with Tofu, Bok Choy & Snap Peas', 'coconut milk', 2, 'can', false),
  ('Thai Red Curry with Tofu, Bok Choy & Snap Peas', 'thai red curry paste', 3, 'tbsp', false),
  ('Thai Red Curry with Tofu, Bok Choy & Snap Peas', 'bok choy', 4, 'cup', false),
  ('Thai Red Curry with Tofu, Bok Choy & Snap Peas', 'snap peas', 1.5, 'cup', false),
  ('Thai Red Curry with Tofu, Bok Choy & Snap Peas', 'bell pepper', 1, 'each', false),
  ('Thai Red Curry with Tofu, Bok Choy & Snap Peas', 'carrot', 1, 'each', false),
  ('Thai Red Curry with Tofu, Bok Choy & Snap Peas', 'thai basil', 0.25, 'cup', true),
  ('Thai Red Curry with Tofu, Bok Choy & Snap Peas', 'lime', 1, 'each', false),
  ('Thai Red Curry with Tofu, Bok Choy & Snap Peas', 'vegetable oil', 2, 'tbsp', false),
  ('Thai Red Curry with Tofu, Bok Choy & Snap Peas', 'white rice', 1.5, 'cup', false),
  ('Thai Red Curry with Tofu, Bok Choy & Snap Peas', 'brown sugar', 1, 'tsp', false),
  ('Thai Red Curry with Tofu, Bok Choy & Snap Peas', 'soy sauce', 1, 'tbsp', false),
  ('Palak Paneer', 'paneer', 8, 'oz', false),
  ('Palak Paneer', 'baby spinach', 5, 'cup', false),
  ('Palak Paneer', 'yellow onion', 1, 'each', false),
  ('Palak Paneer', 'garlic', 3, 'clove', false),
  ('Palak Paneer', 'fresh ginger', 1, 'tbsp', false),
  ('Palak Paneer', 'ground cumin', 1, 'tsp', false),
  ('Palak Paneer', 'garam masala', 1, 'tsp', false),
  ('Palak Paneer', 'ground turmeric', 0.5, 'tsp', false),
  ('Palak Paneer', 'heavy cream', 0.25, 'cup', false),
  ('Palak Paneer', 'ghee', 2, 'tbsp', false),
  ('Palak Paneer', 'kosher salt', 1, 'tsp', false),
  ('Palak Paneer', 'white rice', 1.5, 'cup', true),
  ('Ethiopian-Style Red Lentil Stew (Misir Wot)', 'red lentils', 1.5, 'cup', false),
  ('Ethiopian-Style Red Lentil Stew (Misir Wot)', 'yellow onion', 1, 'each', false),
  ('Ethiopian-Style Red Lentil Stew (Misir Wot)', 'garlic', 4, 'clove', false),
  ('Ethiopian-Style Red Lentil Stew (Misir Wot)', 'fresh ginger', 1, 'tbsp', false),
  ('Ethiopian-Style Red Lentil Stew (Misir Wot)', 'berbere spice blend', 2, 'tbsp', false),
  ('Ethiopian-Style Red Lentil Stew (Misir Wot)', 'crushed tomatoes', 1, 'can', false),
  ('Ethiopian-Style Red Lentil Stew (Misir Wot)', 'vegetable broth', 3, 'cup', false),
  ('Ethiopian-Style Red Lentil Stew (Misir Wot)', 'vegetable oil', 3, 'tbsp', false),
  ('Ethiopian-Style Red Lentil Stew (Misir Wot)', 'kosher salt', 1, 'tsp', false),
  ('Ethiopian-Style Red Lentil Stew (Misir Wot)', 'carrot', 1, 'each', true),
  ('Ethiopian-Style Red Lentil Stew (Misir Wot)', 'white rice', 1.5, 'cup', true)
) as v(recipe_title, ingredient_name, quantity, unit, optional)
join recipes r on r.title = v.recipe_title
join ingredients i on i.name_canonical = v.ingredient_name
on conflict (recipe_id, ingredient_id) do nothing;
